/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AulaPresencialRouteImport } from './routes/aula-presencial'
import { Route as BoxeRouteImport } from './routes/boxe'
import { Route as LocalizacaoRouteImport } from './routes/localizacao'
import { Route as PersonalOnlineRouteImport } from './routes/personal-online'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TreinoPersonalizadoRouteImport } from './routes/treino-personalizado'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AulaPresencialRoute = AulaPresencialRouteImport.update({
  id: '/aula-presencial',
  path: '/aula-presencial',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxeRoute = BoxeRouteImport.update({
  id: '/boxe',
  path: '/boxe',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalizacaoRoute = LocalizacaoRouteImport.update({
  id: '/localizacao',
  path: '/localizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalOnlineRoute = PersonalOnlineRouteImport.update({
  id: '/personal-online',
  path: '/personal-online',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoPersonalizadoRoute = TreinoPersonalizadoRouteImport.update({
  id: '/treino-personalizado',
  path: '/treino-personalizado',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aula-presencial': typeof AulaPresencialRoute
  '/boxe': typeof BoxeRoute
  '/localizacao': typeof LocalizacaoRoute
  '/personal-online': typeof PersonalOnlineRoute
  '/sobre': typeof SobreRoute
  '/treino-personalizado': typeof TreinoPersonalizadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aula-presencial': typeof AulaPresencialRoute
  '/boxe': typeof BoxeRoute
  '/localizacao': typeof LocalizacaoRoute
  '/personal-online': typeof PersonalOnlineRoute
  '/sobre': typeof SobreRoute
  '/treino-personalizado': typeof TreinoPersonalizadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aula-presencial': typeof AulaPresencialRoute
  '/boxe': typeof BoxeRoute
  '/localizacao': typeof LocalizacaoRoute
  '/personal-online': typeof PersonalOnlineRoute
  '/sobre': typeof SobreRoute
  '/treino-personalizado': typeof TreinoPersonalizadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aula-presencial'
    | '/boxe'
    | '/localizacao'
    | '/personal-online'
    | '/sobre'
    | '/treino-personalizado'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aula-presencial'
    | '/boxe'
    | '/localizacao'
    | '/personal-online'
    | '/sobre'
    | '/treino-personalizado'
  id:
    | '__root__'
    | '/'
    | '/aula-presencial'
    | '/boxe'
    | '/localizacao'
    | '/personal-online'
    | '/sobre'
    | '/treino-personalizado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AulaPresencialRoute: typeof AulaPresencialRoute
  BoxeRoute: typeof BoxeRoute
  LocalizacaoRoute: typeof LocalizacaoRoute
  PersonalOnlineRoute: typeof PersonalOnlineRoute
  SobreRoute: typeof SobreRoute
  TreinoPersonalizadoRoute: typeof TreinoPersonalizadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula-presencial': {
      id: '/aula-presencial'
      path: '/aula-presencial'
      fullPath: '/aula-presencial'
      preLoaderRoute: typeof AulaPresencialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxe': {
      id: '/boxe'
      path: '/boxe'
      fullPath: '/boxe'
      preLoaderRoute: typeof BoxeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localizacao': {
      id: '/localizacao'
      path: '/localizacao'
      fullPath: '/localizacao'
      preLoaderRoute: typeof LocalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-online': {
      id: '/personal-online'
      path: '/personal-online'
      fullPath: '/personal-online'
      preLoaderRoute: typeof PersonalOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino-personalizado': {
      id: '/treino-personalizado'
      path: '/treino-personalizado'
      fullPath: '/treino-personalizado'
      preLoaderRoute: typeof TreinoPersonalizadoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AulaPresencialRoute: AulaPresencialRoute,
  BoxeRoute: BoxeRoute,
  LocalizacaoRoute: LocalizacaoRoute,
  PersonalOnlineRoute: PersonalOnlineRoute,
  SobreRoute: SobreRoute,
  TreinoPersonalizadoRoute: TreinoPersonalizadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
